FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    openjdk-21-jre-headless \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
WORKDIR /app

# Copy from root context
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy from the data-ingestion subfolder
COPY data-ingestion/main.py .

RUN mkdir -p /app/data

CMD ["python", "main.py"]